# Configuration for streaming contextual bandit experiments
# This config is optimized for streaming algorithms

# Problem model configuration
PROBLEM_MODEL_TYPE: streaming_synthetic
use_streaming_algorithms: true
use_saved_data: false
use_generated_workers_in_paper: false
only_redo_plots: false
plot: true

# Results and output configuration
RESULTS_DIR: "results/synthetic_paper"

# Embedding configuration
embedding_config:
  model_name: "all-MiniLM-L6-v2"
  dimensions: 50
  suffix: "_all-MiniLM-L6-v2_50-dim"

# Experiment parameters
num_times_to_run: 10
num_rounds: 30000
num_std_to_show: 5
budgets: [1,2,3,4]


# Synthetic agents configuration
synthetic_agents_config:
  specialized_agent_interval: 200
  expert_start_time: 2000
  expert_strength_breakpoint: 6000
  num_expert_dimensions: 5
  num_task_fit_dimensions: 1

# Performance configuration
num_threads_to_use: 10

# Algorithm parameters
v1: 2.23606797749979  # sqrt(5)
v2: 1
rho: 0.9
N: 2
theta: 4.0  # multiplier for variance threshold in CoCoMaMa


# Dataset configuration
streaming_dataset_path: "datasets/synthetic_streaming_30000.arrow"
create_dataset_if_missing: true

# Dataset paths for synthetic generation (if needed)
sprout_streaming_path: "datasets/sprout_streaming_30000.arrow"
synthetic_dataset_path: "datasets/synthetic_streaming_50dim_30000rounds.arrow"
